### ISSUE TITLE
Initial Release Prep

### ISSUE THREAD

**Issue by marksmccann** [marksmccann/node-sass-extra#50]
- [ ] add relevant badges to readme
- [x] perform initial versioning and create changelog &mdash; [example](https://github.com/conventional-changelog/standard-version#first-release)
- [x] setup npm script for publishing to NPM
- [ ] update CI to update version, create tags and publish on Merge with Master

Should we consider doing a -prerelease or -beta version as we figure this out? I am guessing we are not gonna get it the first time out.

**Comment by marksmccann** [comment]
@phillipluther I opened up this issue for us to button up our project and get it published. I made a check list of the steps I believe are left. Feel free to update the list if I got something wrong or missed something.

**Comment by phillipluther** [comment]
I like the idea of -prerelease ... I think there will be hiccups with publishing, too. NPM doesn't let you overwrite/force the way Git does, so any errant attempts will forever show up in the project history.

The "setup npm script for publishing" should definitely be last so we can make sure everything at least _looks_ correct.

**Comment by marksmccann** [comment]
We have other open issues for the remaining checkboxes, closing this one.
